<?php

use Laravel\Roster\Enums\Packages;
use Laravel\Roster\Package;
use Laravel\Roster\Scanners\YarnPackageLock;

$yarnOnlyPath = __DIR__.'/../../fixtures/yarn-only/';

beforeEach(function () use ($yarnOnlyPath) {
    if (! is_dir($yarnOnlyPath)) {
        mkdir($yarnOnlyPath, 0755, true);
    }
});

afterEach(function () use ($yarnOnlyPath) {
    if (file_exists($yarnOnlyPath.'yarn.lock')) {
        unlink($yarnOnlyPath.'yarn.lock');
    }
    if (is_dir($yarnOnlyPath)) {
        rmdir($yarnOnlyPath);
    }
});

it('detects scoped npm packages in yarn.lock', function () use ($yarnOnlyPath) {
    // Create a yarn.lock with scoped packages
    $yarnLockContent = <<<'YARN'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@inertiajs/react@^2.0.12":
  version "2.0.12"
  resolved "https://registry.yarnpkg.com/@inertiajs/react/-/react-2.0.12.tgz"
  integrity sha512-abc123

"@laravel/vite-plugin-wayfinder@^0.1.0":
  version "0.1.0"
  resolved "https://registry.yarnpkg.com/@laravel/vite-plugin-wayfinder/-/vite-plugin-wayfinder-0.1.0.tgz"
  integrity sha512-def456

tailwindcss@^3.4.3:
  version "3.4.16"
  resolved "https://registry.yarnpkg.com/tailwindcss/-/tailwindcss-3.4.16.tgz"
  integrity sha512-xyz789

react@^19.1.0:
  version "19.1.0"
  resolved "https://registry.yarnpkg.com/react/-/react-19.1.0.tgz"
  integrity sha512-ghi012

YARN;

    file_put_contents($yarnOnlyPath.'yarn.lock', $yarnLockContent);

    $scanner = new YarnPackageLock($yarnOnlyPath);
    $items = $scanner->scan();

    // Check that scoped packages are detected
    $inertiaReact = $items->first(
        fn ($item) => $item instanceof Package && $item->package() === Packages::INERTIA_REACT
    );

    $tailwind = $items->first(
        fn ($item) => $item instanceof Package && $item->package() === Packages::TAILWINDCSS
    );

    expect($inertiaReact)->not->toBeNull('Expected @inertiajs/react to be detected')
        ->and($inertiaReact->version())->toEqual('2.0.12')
        ->and($tailwind)->not->toBeNull('Expected tailwindcss to be detected')
        ->and($tailwind->version())->toEqual('3.4.16');
});

it('detects unquoted scoped packages in yarn.lock', function () use ($yarnOnlyPath) {
    // Some yarn versions may not quote the package names
    $yarnLockContent = <<<'YARN'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


@inertiajs/vue3@^2.0.0:
  version "2.0.5"
  resolved "https://registry.yarnpkg.com/@inertiajs/vue3/-/vue3-2.0.5.tgz"
  integrity sha512-abc123

alpinejs@^3.4.2:
  version "3.4.4"
  resolved "https://registry.yarnpkg.com/alpinejs/-/alpinejs-3.4.4.tgz"
  integrity sha512-def456

YARN;

    file_put_contents($yarnOnlyPath.'yarn.lock', $yarnLockContent);

    $scanner = new YarnPackageLock($yarnOnlyPath);
    $items = $scanner->scan();

    $inertiaVue = $items->first(
        fn ($item) => $item instanceof Package && $item->package() === Packages::INERTIA_VUE
    );

    $alpine = $items->first(
        fn ($item) => $item instanceof Package && $item->package() === Packages::ALPINEJS
    );

    expect($inertiaVue)->not->toBeNull('Expected @inertiajs/vue3 to be detected')
        ->and($inertiaVue->version())->toEqual('2.0.5')
        ->and($alpine)->not->toBeNull('Expected alpinejs to be detected')
        ->and($alpine->version())->toEqual('3.4.4');
});
